on: [push] # Déclenche l'action en réponse à un événement "push" dans le référentiel GitHub.

jobs:
  deploy: # Définition d'un job nommé "deploy".
    runs-on: ubuntu-latest # Spécifie que ce job s'exécutera sur une machine virtuelle Ubuntu.

    name: Deploy my nice code # Donne un nom lisible au job.

    steps: # Définition des étapes à suivre dans ce job.

      - name: Deploy to OVH hosting # Étape de déploiement vers l'hébergement OVH.
        uses: pitscher/ovh-deploy-hosting-action@v1 # Utilise l'action "ovh-deploy-hosting-action" de la version 1 du référentiel "pitscher".

        env: # Définition des variables d'environnement pour l'action.
          OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }} # Utilise une variable secrète "OVH_HOSTING_USER" pour l'identifiant OVH.
          OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }} # Utilise une variable secrète "OVH_HOSTING_PASSWORD" pour le mot de passe OVH.
          OVH_HOSTING_DOMAIN: ssh.cluster027.hosting.ovh.net # Spécifie le domaine de l'hébergement OVH.
          REPOSITORY_NAME: client_frontend # Le nom du référentiel à déployer.
          REPOSITORY_URL: https://github.com/DigitalExpresse/client_frontend.git # L'URL du référentiel source sur GitHub.


      - name: install dependencies and build
        run: |
          ls
          cd client_frontend
          source ~/.nvm/nvm.sh
          npm install
          npm run build
        

    


