on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy my nice code

    steps:
      - name: Deploy to OVH hosting
        uses: pitscher/ovh-deploy-hosting-action@v1
        env:
          OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
          OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
          OVH_HOSTING_DOMAIN: ssh.cluster027.hosting.ovh.net
          REPOSITORY_NAME: client_frontend
          REPOSITORY_URL: https://github.com/DigitalExpresse/client_frontend.git

      - name: Check previous step result
        id: check_result
        run: echo ::set-output name=deploy-success::true
        if: ${{ success() }}

      - name: Install dependencies and build
        run: |
          source ~/.nvm/nvm.sh
          cd client_frontend  # Change directory to the correct path
          npm install
          npm run build
        if: steps.check_result.outputs.deploy-success == 'true'
